service: cicd-1

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  stage: dev
  memorySize: 128
  timeout: 2

functions:
  loggingFn:
    handler: logger.log
    events:
      - http:
          path: test/log
          method: get

